/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Aug-2017 9:56:16 AM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TB_Administrator_TB_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TB_Administrator] DROP CONSTRAINT [FK_TB_Administrator_TB_Roles]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TB_Manager_TB_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TB_Manager] DROP CONSTRAINT [FK_TB_Manager_TB_Roles]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TB_User_TB_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TB_User] DROP CONSTRAINT [FK_TB_User_TB_Roles]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_Administrator]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_Administrator]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_Manager]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_Manager]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_Roles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_Roles]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_Trainee]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_Trainee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_User]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_User]
GO

/* Create Tables */

CREATE TABLE [TB_Administrator]
(
	[AdministratorID] int NOT NULL,
	[Name] varchar(50) NULL,
	[DOB] decimal(8) NULL,
	[Status] varchar(1) NULL,
	[RolesID] int NULL
)
GO

CREATE TABLE [TB_Manager]
(
	[ManagerID] int NOT NULL,
	[Name] varchar(50) NULL,
	[DOB] decimal(8) NULL,
	[RolesID] int NULL
)
GO

CREATE TABLE [TB_Roles]
(
	[RolesID] int NOT NULL,
	[RolesName] varchar(15) NULL,
	[UserID] int NULL
)
GO

CREATE TABLE [TB_Trainee]
(
	[TraineeID] int NOT NULL,
	[Name] varchar(50) NULL,
	[DOB] decimal(8) NULL,
	[Status] varchar(1) NULL,
	[TrainingID] int NULL,
	[RolesID] int NULL
)
GO

CREATE TABLE [TB_User]
(
	[UserID] int NOT NULL,
	[Name] varchar(50) NULL,
	[Username] varchar(15) NULL,
	[Password] varchar(15) NULL,
	[DOB] decimal(8) NULL,
	[RolesID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [TB_Administrator] 
 ADD CONSTRAINT [PK_TB_Administrator]
	PRIMARY KEY CLUSTERED ([AdministratorID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TB_Administrator_TB_Roles] 
 ON [TB_Administrator] ([RolesID] ASC)
GO

ALTER TABLE [TB_Manager] 
 ADD CONSTRAINT [PK_TB_Manager]
	PRIMARY KEY CLUSTERED ([ManagerID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TB_Manager_TB_Roles] 
 ON [TB_Manager] ([RolesID] ASC)
GO

ALTER TABLE [TB_Roles] 
 ADD CONSTRAINT [PK_TB_Roles]
	PRIMARY KEY CLUSTERED ([RolesID] ASC)
GO

ALTER TABLE [TB_Trainee] 
 ADD CONSTRAINT [PK_TB_Trainee]
	PRIMARY KEY CLUSTERED ([TraineeID] ASC)
GO

ALTER TABLE [TB_User] 
 ADD CONSTRAINT [PK_TB_User]
	PRIMARY KEY CLUSTERED ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TB_User_TB_Roles] 
 ON [TB_User] ([RolesID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [TB_Administrator] ADD CONSTRAINT [FK_TB_Administrator_TB_Roles]
	FOREIGN KEY ([RolesID]) REFERENCES [TB_Roles] ([RolesID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [TB_Manager] ADD CONSTRAINT [FK_TB_Manager_TB_Roles]
	FOREIGN KEY ([RolesID]) REFERENCES [TB_Roles] ([RolesID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [TB_User] ADD CONSTRAINT [FK_TB_User_TB_Roles]
	FOREIGN KEY ([RolesID]) REFERENCES [TB_Roles] ([RolesID]) ON DELETE No Action ON UPDATE No Action
GO
